### ISSUE TITLE
Adjustments needed to support non-Arduino builds for SCAMP encode/decode

### ISSUE THREAD

**Issue by brucemack** [profdc9/RFBitBanger#4]
Issue created to track a few minor adjustments that will allow the SCAMP encode/decode to be built outside of the Arduino environment.

**Comment by profdc9** [comment]
I pulled your request and merged it with the main line after a few modifications.  Please check it out and if its satisfactory, close the PR.

**Comment by brucemack** [comment]
Looks good, many thanks!
